theme: jekyll-theme-cayman
title: "Title of the project goes here"
description: "Subtitle/description which comes after title goes here"
show_downloads: true # displays download button on the .io page
